"""add video process task table

Revision ID: 4f0f4c980237
Revises: 93ae13d3e2b9
Create Date: 2025-10-09 23:38:59.123362

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4f0f4c980237"
down_revision: Union[str, Sequence[str], None] = "93ae13d3e2b9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "video_merge_tasks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_rtsp_path", sa.String(), nullable=False),
        sa.Column("start_time", sa.String(), nullable=False),
        sa.Column("end_time", sa.String(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "processing", "completed", "error", name="taskstatus"),
            nullable=False,
        ),
        sa.Column("message", sa.String(), nullable=True),
        sa.Column("result_video_path", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("video_merge_tasks")
    # ### end Alembic commands ###
